homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Stockholm
#  customize: !include_dir_merge_named customize
#  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password

frontend:
config:
mobile_app:
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  server_port: 443

cloud:

# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
map:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:

system_health:

recorder:
  purge_interval: 2
  purge_keep_days: 5

########################################
###               HUBS               ###
########################################

tellstick:
  host: core-tellstick
  port: [50800, 50801]
zwave:
  usb_path: /dev/ttyACM0
#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - mac: !secret xiaomi_mac
#      key: !secret xiaomi_key
#      host: 192.168.1.209

nibe:
  systems:
    - system: 77687
      units:
        - unit: 0
          categories: True
          statuses: True
      climates: True
      water_heaters: True
      fans: True

#tts:
#  platform: google

sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
light:
  - platform: switch
    name: Fönsterlampa klädkammare
    entity_id: switch.fonsterlampa_kladkammare
  - platform: switch
    name: Spegellampa
    entity_id: switch.spegellampa
  - platform: switch
    name: Sovrumslampa
    entity_id: switch.bedroom_switch
  - platform: switch
    name: Vardagsrum
    entity_id: switch.vardagsrum
  - platform: switch
    name: Trädgård
    entity_id: switch.lampor_baksidan
  - platform: switch
    name: Korridor
    entity_id: switch.hallway_switch

#device_tracker:
#  - platform: nmap_tracker
#    hosts: !secret nmap_tracker_hosts
#    track_new_devices: false
#    interval_seconds: 20
#    consider_home: 20
#    home_interval: 10
#    exclude:
#      - !secret hass_wlan_ip
#  - platform: owntracks_http

#zone:
#  - name: Carola School
#    latitude: !secret carola_school_lat
#    longitude: !secret carola_school_long
#    icon: mdi:school
#    radius: 200
#  - name: Peter Work
#    latitude: !secret work_lat
#    longitude: !secret work_long
#    icon: mdi:briefcase
#    radius: 300
#  - name: Home
#    latitude: !secret home_lat
#    longitude: !secret home_long
#    icon: mdi:home
#    radius: 100

automation: !include_dir_merge_list automation
#group: !include_dir_merge_named group/

#notify:
#  - name: Pushbullet Peter
#    platform: pushbullet
#    api_key: !secret pushbullet_key_peter

#input_boolean:
#  peter_home:
#    name: Peter home
#    initial: on
#    icon: mdi:cellphone-iphone
#  carola_home:
#    name: Carola home
#    initial: on
#    icon: mdi:cellphone-iphone

binary_sensor:
  - platform: template
    sensors:
      tv_livingroom_state:
        friendly_name: "TV vardagsrum"
        delay_off:
          seconds: 5
        value_template: >-
          {{ states('sensor.tv_power')|float > 30 }}
      dishwasher_state:
        friendly_name: "Diskmaskin"
        delay_off:
          minutes: 2
        value_template: >-
          {{ states('sensor.diskmaskin_switch_power')|float > 2 }}