homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize:
    group.all_automations:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_devices:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_switches:
      hidden: false
    sensor.disk_used_:
      friendly_name: Rpi Disk Used
#    sensor.process_mosquitto:
#      friendly_name: 'Mosquitto'
#      hidden: False
#      icon: mdi:message-processing
#    sensor.process_homebridge:
#      friendly_name: 'Apple HomeKit'
#      hidden: False
#      icon: mdi:apple
    sensor.uptime:
      friendly_name: 'Hass Uptime'
    sensor.ha_uptime:
      friendly_name: 'Hass Up Since'
      icon: mdi:timetable
    input_boolean.notify_peter:
      icon: mdi:message-bulleted
      confirm_controls_show_lock: true
    input_text.peter_notify_text:
      icon: mdi:message-bulleted

#  customize_glob: !include customglob.yaml
#  packages: !include_dir_named packages

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# ########################################
# ###                GUI               ###
# ########################################

frontend:
#map:

# ########################################
# ###              LOGGING             ###
# ########################################

# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:

recorder:
  purge_interval: 2
  purge_keep_days: 5

########################################
###               HUBS               ###
########################################

tellstick:
zwave:
  usb_path: /dev/zwave

# Text to speech
#tts:
#  platform: google

sensor: !include_dir_merge_list sensor
#light: !include_dir_merge_list lights
switch: !include_dir_merge_list switch
#scene: !include_dir_merge_list scene
device_tracker: !include device_tracker.yaml
#zone:
#  - name: Carola School
#    latitude: !secret school_lat
#    longitude: !secret school_long
#    icon: mdi:code-braces
#  - name: Peter Work
#    latitude: !secret work_lat
#    longitude: !secret work_long
#    icon: mdi:briefcase
#    radius: 300

# ########################################
# ###             SERVICES             ###
# ########################################
#automation: !include_dir_merge_list automation
notify: !include notify.yaml
#python_script:
#script: !include scripts.yaml
group: !include_dir_merge_named group/


automation:
  - alias: Notify Peter
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.notify_peter
      to: 'on'
    action:
      - service: notify.pushbullet_peter
        data:
          message: ''
          title: '{{ states.input_text.peter_notify_text.state }}'
      - service: homeassistant.turn_off
        entity_id: input_boolean.notify_peter

input_boolean:
  notify_peter:
    name: Send
    initial: 'off'

input_text:
  peter_notify_text:
    name: Peter Notify Text
    initial: Fem minuter till mat
