homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 55
  unit_system: metric
  time_zone: Europe/Stockholm
  external_url: "https://k33.duckdns.org"
  internal_url: "https://k33.duckdns.org"

  customize:
    sensor.tv_energy:
      device_class: energy
      state_class: total_increasing
    sensor.tv_power:
      device_class: power
      state_class: measurement
    sensor.diskmaskin_switch_energy:
      device_class: energy
      state_class: total_increasing
    sensor.diskmaskin_switch_power:
      device_class: power
      state_class: measurement
    sensor.torktumlare_energy:
      device_class: energy
      state_class: total_increasing
    sensor.tvattmaskin_energy:
      device_class: energy
      state_class: total_increasing

frontend:
config:
mobile_app:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

cloud:

energy:

# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
map:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:

system_health:

recorder:
  purge_keep_days: 5

# Hubs
tellstick:
  host: core-tellstick
  port: [50800, 50801]
zwave:
  usb_path: /dev/ttyACM0

# Nibe F370
nibe:
  systems:
    - system: 77687
      units:
        - unit: 0
          categories: True
          statuses: True
      climates: True
      water_heaters: True
      fans: True

sensor: !include_dir_merge_list sensor

switch:
  - platform: tellstick

light:
  - platform: switch
    name: Fönsterlampa klädkammare
    entity_id: switch.fonsterlampa_kladkammare
  - platform: switch
    name: Spegellampa
    entity_id: switch.spegellampa
  - platform: switch
    name: Sovrumslampa
    entity_id: switch.bedroom_switch
  - platform: switch
    name: Vardagsrum
    entity_id: switch.vardagsrum
  - platform: switch
    name: Trädgård
    entity_id: switch.lampor_baksidan
  - platform: switch
    name: Korridor
    entity_id: switch.hallway_switch

automation: !include automations.yaml

binary_sensor:
  - platform: template
    sensors:
      tv_livingroom_state:
        friendly_name: "TV vardagsrum"
        delay_off:
          seconds: 5
        value_template: >-
          {{ states('sensor.tv_power')|float > 30 }}
      dishwasher_state:
        friendly_name: "Diskmaskin"
        delay_off:
          minutes: 2
        value_template: >-
          {{ states('sensor.diskmaskin_switch_power')|float > 2 }}

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.1.111
  port: 8086
  token: lKDiEHCAs0acHTPSBVwXBp93nG9KKWCOCrdJd5Yp78vCeeYPE7nkYVV0uoxD869qhIMib6Xb9g3zlhd8X8BKOA==
  organization: 249466701622a2ea
  bucket: home_assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
#  exclude:
#    entities:
#      - zone.home
#    domains:
#      - persistent_notification
#      - person
  include:
#    domains:
#      - sensor
    entities:
      - sensor.diskmaskin_switch_power
      - sensor.diskmaskin_switch_energy
      - sensor.tv_energy
      - sensor.tv_power