- alias: 'Peter Away'
  condition:
    condition: state
    entity_id: input_boolean.peter_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.petergalaxys7
      to: 'not_home'
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.peter_telefon
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.peter_home

- alias: 'Peter Home'
  condition:
    condition: state
    entity_id: input_boolean.peter_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.petergalaxys7
      to: 'home'
    - platform: state
      entity_id: device_tracker.peter_telefon
      to: 'home'
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.peter_home

- alias: 'Carola Away'
  condition:
    condition: state
    entity_id: input_boolean.carola_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.carolahonor8
      to: 'not_home'
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.carola_telefon
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.carola_home

- alias: 'Carola Home'
  condition:
    condition: state
    entity_id: input_boolean.carola_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.carolahonor8
      to: 'home'
    - platform: state
      entity_id: device_tracker.carola_telefon
      to: 'home'
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.carola_home