- alias: 'Morning lights weekday'
  trigger:
    - platform: time
      at: "06:50:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare
    - service: light.turn_on
      data:
        entity_id: light.sovrumslampa
    - service: light.turn_on
      data:
        entity_id: light.korridor

#----------
- alias: 'Morning lights weekend'
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare
    - service: light.turn_on
      data:
        entity_id: light.korridor

#----------
- alias: 'No lights at day'
  trigger:
    - platform: time
      at: "08:10:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_off
      data:
        entity_id: light.vardagsrum
    - service: light.turn_off
      data:
        entity_id: light.spegellampa
    - service: light.turn_off
      data:
        entity_id: light.fonsterlampa_kladkammare
    - service: light.turn_off
      data:
        entity_id: light.korridor
    - service: light.turn_off
      data:
        entity_id: light.sovrumslampa

#----------
- alias: 'Afternoon lights'
  trigger:
    - platform: time
      at: "16:00:00"
#    - platform: sun
#      event: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.korridor
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum_tv_lampa

#----------
- alias: 'Evening bedroom lights'
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.sovrumslampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare

#----------
- alias: 'Evening Carola bed light'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_livingroom_state
      to: 'off'
  condition:
    - condition: state
      entity_id: sensor.battery_state
      state: 'discharging'
    - condition: time
      after: '21:00:00'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 20
        entity_id: light.bedroom_carola

#----------
- alias: 'Evening Peter bed light'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_livingroom_state
      to: 'off'
  condition:
    - condition: state
      # Kollar Carloas telefon
      entity_id: sensor.battery_state
      state: 'discharging'
    - condition: time
      after: '21:00:00'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 20
        entity_id: light.sovrum_peter

#----------
- alias: 'Turn off korridor at night'
  trigger:
    - platform: time
      at: "21:30:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.korridor

#----------
- alias: 'Yard lights on'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.tradgard

#----------
- alias: 'Yard lights off'
  trigger:
    - platform: time
      at: "23:50:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.tradgard