- alias: 'Morning lights weekday'
  trigger:
    - platform: time
      at: "07:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum
    - service: switch.turn_on
      data:
        entity_id: switch.spegellampa
    - service: switch.turn_on
      data:
        entity_id: switch.fonsterlampa_kladkammare

- alias: 'Morning lights weekend'
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum
    - service: switch.turn_on
      data:
        entity_id: switch.spegellampa
    - service: switch.turn_on
      data:
        entity_id: switch.fonsterlampa_kladkammare

- alias: 'No lights at day'
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: device_tracker.petergalaxys7
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.carolahonor8
      state: 'not_home'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.vardagsrum
    - service: switch.turn_on
      data:
        entity_id: switch.spegellampa
    - service: switch.turn_on
      data:
        entity_id: switch.fonsterlampa_kladkammare

- alias: 'Evening lights'
  trigger:
    - platform: time
      at: "16:30:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum
    - service: switch.turn_on
      data:
        entity_id: switch.spegellampa
    - service: switch.turn_on
      data:
        entity_id: switch.fonsterlampa_kladkammare

- alias: 'Outside back lights on'
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.lampor_baksidan

- alias: 'Outside back lights off'
  trigger:
    - platform: time
      at: "22:30:00"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.lampor_baksidan