- alias: 'Morning lights weekday'
  trigger:
    - platform: time
      at: "06:50:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare
    - service: light.turn_on
      data:
        entity_id: light.sovrumslampa

- alias: 'Morning korridor lights weekday'
  trigger:
    - platform: time
      at: "07:05:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.korridor

- alias: 'Morning lights weekend'
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare

- alias: 'Morning korridor lights weekend'
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        entity_id: light.korridor

- alias: 'No lights at day'
  trigger:
    - platform: time
      at: "08:10:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_off
      data:
        entity_id: light.vardagsrum
    - service: light.turn_off
      data:
        entity_id: light.spegellampa
    - service: light.turn_off
      data:
        entity_id: light.fonsterlampa_kladkammare
    - service: light.turn_off
      data:
        entity_id: light.korridor
    - service: light.turn_off
      data:
        entity_id: light.sovrumslampa

- alias: 'Evening sunset lights'
  trigger:
    - platform: time
      at: "18:30:00"
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.vardagsrum
    - service: light.turn_on
      data:
        entity_id: light.spegellampa
    - service: light.turn_on
      data:
        entity_id: light.korridor

- alias: 'Evening sunset bedroom lights'
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.sovrumslampa
    - service: light.turn_on
      data:
        entity_id: light.fonsterlampa_kladkammare

- alias: 'Turn off korridor at night'
  trigger:
    - platform: time
      at: "21:30:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.korridor


#- alias: 'Outside back lights on'
#  trigger:
#    - platform: time
#      at: "20:00:00"
#  action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.lampor_baksidan
#
#- alias: 'Outside back lights off'
#  trigger:
#    - platform: time
#      at: "22:30:00"
#  action:
#    - service: switch.turn_off
#      data:
#        entity_id: switch.lampor_baksidan