- alias: 'Morning lights'
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum

- alias: 'No lights at day'
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: device_tracker.petergalaxys7
      state: 'not_home'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.vardagsrum

- alias: 'Evening lights'
  trigger:
    - platform: time
      at: "16:30:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.vardagsrum

- alias: 'Outside back lights on'
  trigger:
    - platform: time
      at: "17:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.lampor_baksidan

- alias: 'Outside back lights off'
  trigger:
    - platform: time
      at: "23:30:00"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.lampor_baksidan