- alias: 'Peter is home'
  trigger:
    platform: state
    entity_id: input_boolean.peter_home
    from: 'off'
    to: 'on'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Peter is now home'
- alias: 'Peter is away'
  trigger:
    platform: state
    entity_id: input_boolean.peter_home
    from: 'on'
    to: 'off'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Peter has left home'

- alias: 'Carola is home'
  trigger:
    platform: state
    entity_id: input_boolean.carola_home
    from: 'off'
    to: 'on'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Carola is now home'
- alias: 'Carola is away'
  trigger:
    platform: state
    entity_id: input_boolean.carola_home
    from: 'on'
    to: 'off'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Carola has left home'

- alias: 'Carola is at school'
  trigger:
    platform: zone
    entity_id: device_tracker.carola_telefon
    zone: zone.carola_school
    event: enter
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Carola is at school'
- alias: 'Carola left school'
  trigger:
    platform: zone
    entity_id: device_tracker.carola_telefon
    zone: zone.carola_school
    event: leave
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Carola has left school'
