- alias: 'Peter is home'
  trigger:
    platform: state
    entity_id: device_tracker.petergalaxys7lan
    from: 'not_home'
    to: 'home'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Peter is now home'
- alias: 'Peter is away'
  trigger:
    platform: state
    entity_id: device_tracker.petergalaxys7lan
    from: 'home'
    to: 'not_home'
  action:
    service: notify.pushbullet_peter
    data:
      message: 'Peter has left home'