- alias: 'Turn off with remote'
  trigger:
    platform: state
    entity_id: switch.remote1
    to: 'off'
  action:
      - service: switch.turn_on
        data:
          entity_id: switch.remote1
      - delay: '00:00:05'
      - service: switch.turn_off
        data:
          entity_id: switch.vardagsrum
      - delay: '00:00:05'
      - service: switch.turn_off
        data:
          entity_id: switch.lampor_baksidan
