- alias: 'Turn off with remote'
  trigger:
    platform: state
    entity_id: switch.remote1
    to: 'off'
  action:
      - delay:
        seconds: 15
      - service: switch.turn_off
        data:
          entity_id: switch.vardagsrum
