- alias: 'No TV at night'
  trigger:
    - platform: time
      at: "23:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.tv_switch

- alias: 'No TV at night weekend'
  trigger:
    - platform: time
      at: "23:59:00"
  condition:
    - condition: time
      weekday:
        - fri
        - sat
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.tv_switch

- alias: 'TV on at day'
  trigger:
    - platform: time
      at: "16:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.tv_switch

- alias: 'TV on at day weekend'
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.tv_switch
