#homeassistant:

automation:
## Turn on outside lights and living room light at sunset
  - alias: Lights On Outside And Living room At Sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_dark

## Turn off outside lights and living room light at midnight
  - alias: Lights Off Outside And Living room At Midnight
    trigger:
      platform: time
      at: '23:59:00'
    action:
#      - service: light.turn_off
#        data:
#          entity_id: light.outside_front_light
#          transition: 30
#      - service: light.turn_off
#        data:
#          entity_id: light.outside_yard_light
#          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.living_room_light
#          transition: 30
#      - service: light.turn_off
#        entity_id: light.outside_yard_hanging_lights
