homeassistant:
  customize:
    input_boolean.notify_peter:
      icon: mdi:message-bulleted
      confirm_controls_show_lock: true
    input_text.peter_notify_text:
      icon: mdi:message-bulleted

automation:
  - alias: Notify Peter
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.notify_peter
      to: 'on'
    action:
      - service: notify.pushbullet_peter
        data:
          message: ''
          title: '{{ states.input_text.peter_notify_text.state }}'
      - service: homeassistant.turn_off
        entity_id: input_boolean.notify_peter

input_boolean:
  notify_peter:
    name: Send
    initial: 'off'

input_text:
  peter_notify_text:
    name: Peter Notify Text
    initial: Fem minuter till mat
