homeassistant:
  customize:
    sensor.uptime:
      friendly_name: 'Hass Uptime'

group:
  system_monitor_card:
    name: System Monitor Hass Rpi
    entities:
      - sensor.uptime

sensor:
  - platform: uptime
    unit_of_measurement: hours
